### ISSUE TITLE
Feature: Home & Action Menu

### ISSUE THREAD

**Issue by chrysloi** [atlp-rwanda/commanders-rn-medica#17]
# Home & Action Menu

#### Description

As a developer, I want to create a comprehensive UI for the Home screen and the action menu which will be a bottom sheet navigation.

#### Tasks

- [x] Create a bottom sheet navigation
- [ ] Create a home screen focusing on the given design
- [ ] Add every action menu as shown on the UI
- [ ] Give every menu a related icon

#### Definition of Done

- The bottom sheet navigation allows to navigate through screens
- The home screen look exactly as the UI design considering the details.

![Image](https://github.com/atlp-rwanda/commanders-rn-medica/assets/99283140/312c6bc5-a0c0-4f1d-bb9a-21da02e6c9ea)
