### ISSUE TITLE
Feat: Fill your profile screens

### ISSUE THREAD

**Issue by justinmihigo** [atlp-rwanda/commanders-rn-medica#20]
#### Description

As a developer, I want to create a comprehensive UI for the Fill up screen

#### Tasks

- [x] Use an image picker for profile selection
- [x] Creating the fill up screen
- [x] Use date picker

#### Definition of Done

- The user should be able to fill up the information in all fields
- The user should be able to select a photo from the gallery
![image](https://github.com/atlp-rwanda/commanders-rn-medica/assets/118519513/0ab76ab6-eafb-466c-8c33-6065b6b35592)
