### ISSUE TITLE
Feat: forgot & reset password screens designs

### ISSUE THREAD

**Issue by fredshema** [atlp-rwanda/commanders-rn-medica#26]
#### Description

A user of the app might forget their password. In that case they need a place where they can reset their password in a secure way.

#### Tasks

- [x] Design forgot password screen
- [x] Design OTP code verification screen
- [x] Design create new password screen 
- [x] Design password reset success screen

#### Developer Notes

Since the styling framework is not already setup i will be using the usual css and this will be refactored once it is merged in the `dev` branch.

#### Related Issues

- N/A

#### Screens to be implemented

<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/622b3a30-d945-4d52-8bf4-37ee52d569e1" width="180"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/ee7aa7e4-bf05-418e-968a-d0d905f3b3da" width="180"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/d387e10a-e1a6-4fdb-99d2-d120cedadc32" width="180"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/53a1229d-a927-42a8-905b-24072a0e2585" width="180"/>

#### Definition of Done

- All screens looks and behaves as the designs
- Navigation between screens works perfectly
