### ISSUE TITLE
Feature: notifications screen design

### ISSUE THREAD

**Issue by fredshema** [atlp-rwanda/commanders-rn-medica#29]
#### Description

Because of many interactions in the app users need somewhere to be notified on actions that happened to their account. This notifications page will include all activities details, and announcements that are related to the logged in user.

#### Tasks

- [x] Design the interface
- [x] Import required icons
- [x] Extend the NavigationHeader component

#### Developer Notes

N/A

#### Related Issues

- N/A

#### Screens to be implemented

<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/e3081084-080d-4d53-9b69-b54678637a75" width="180"/>

#### Definition of Done

- All screens looks and behaves as the designs
