### ISSUE TITLE
Feature: Add Create PIN and set up fingerprint screens

### ISSUE THREAD

**Issue by justinmihigo** [atlp-rwanda/commanders-rn-medica#40]
#### Description

As a developer, I want to create a comprehensive UI of the screens for creating pin and set up fingerprint and set up a modal that pop up when he finishes.

#### Tasks

- [x] Create screen for a user to create pin
- [x] Create a screen for a user to set up fingerprint
- [x] Create a popup that comes when a user finishes to create the pin or fingerprint

#### Definition of Done

- The user should be able to use a fingerprint
- The user should be able to create a new pin
- The user should be able to see a modal that shows that setting up those two things was successful
#### Screenshots
![image](https://github.com/atlp-rwanda/commanders-rn-medica/assets/118519513/cc3b6e4d-4c44-4f9e-82e7-3860b5210743)
![image](https://github.com/atlp-rwanda/commanders-rn-medica/assets/118519513/36f32c69-9eb4-468b-8773-025aab865295)
![image](https://github.com/atlp-rwanda/commanders-rn-medica/assets/118519513/8d77fbc2-ed37-4ad4-ad68-5376050f4fd1)
