### ISSUE TITLE
Feature: Doctor appointment (Booking for online consultation) screens

### ISSUE THREAD

**Issue by fredshema** [atlp-rwanda/commanders-rn-medica#46]
#### Description

A user can book a doctor consultation and select the most convenient time a doctor is available. They can also select a package that is affordable.

#### Tasks

- [x] Design doctor details screen
- [x] Design ratings & reviews screen
- [x] Design book appointment screen
- [x] Design Packages screen
- [x] Design Patients details screen 

#### Developer Notes

N/A

#### Related Issues

- N/A

#### Screens to be implemented

<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/c2fa69d0-80b5-41e6-925a-bdf7423674b8" width="150"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/3dd3a068-ca45-433a-97f2-e89bf0562303" width="150"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/f78bf405-f945-4f95-b226-5445ade2e25d" width="150"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/dcf40ae5-50be-4bd1-b580-2201338566ae" width="150"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/728a1e05-9195-460b-8f2f-bab905e9eb29" width="150"/>

#### Definition of Done

- All screens looks and behaves as the designs
- Navigation between pages works correctly
