### ISSUE TITLE
Chore: Setting up testing tools

### ISSUE THREAD

**Issue by fredshema** [atlp-rwanda/commanders-rn-medica#5]
#### Description

We need testing tools to help us test the app in a clear and concise way. 

#### Tasks

- [x] Outline tools to be used
- [x] Install required dependencies
- [x] Create and setup required config files
- [x] Add testing script in `package.json`

#### Developer Notes

- I used this [guide](https://medium.com/aia-sg-techblog/guide-to-react-native-testing-library-608feadc82df) to setup these testing tools
- If there is a testing package you think we can add, feel free to chime in.

#### Related Issues

- N/A

#### Definition of Done

- All dependencies are installed with no conflicts
- All required config files are present
