### ISSUE TITLE
Feature: Chat history screens

### ISSUE THREAD

**Issue by justinmihigo** [atlp-rwanda/commanders-rn-medica#51]
#### Description

As a developer, I want to create a comprehensive UI of the screens for chat history between a user and a doctor

#### Tasks

- [x] Create screen for a user to get all history with the assigned health care practitioner
- [x] Create a screen for viewing a single message and all the past conversations
- [x] Create a small model for more options like exporting chats, deleting the conversations.

#### Definition of Done

- The user should be able to see all the conversations took place with the health care practitioner.
- The user should be able to see a single conversation and all the messages written.
- A user should be able to see the options to delete or export the chats
#### Screenshots
![image](https://github.com/atlp-rwanda/commanders-rn-medica/assets/118519513/e06c405f-a32a-4248-b107-54b39d5bf2a9)
