### ISSUE TITLE
Feature: doctor appointment payment screens

### ISSUE THREAD

**Issue by fredshema** [atlp-rwanda/commanders-rn-medica#64]
#### Description

A user can book a doctor consultation and select the most convenient time a doctor is available. They can also select a package that is affordable.

#### Tasks

- [x] Design select payment methods screen
- [x] Design add new card screen
- [x] Design summary screen
- [x] Design success & failed state screens

#### Developer Notes

N/A

#### Related Issues

- N/A

#### Screens to be implemented

<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/646af359-9431-43ad-8fe9-521922f6c417" width="150"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/36aaabb7-06d2-48f5-b13f-231d9f19f787" width="150"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/c8c7d2a0-2974-4369-965f-87a64dccc648" width="150"/>

#### Definition of Done

- All screens looks and behaves as the designs
- Navigation between pages works correctly
