### ISSUE TITLE
Feature: Voice Call history screen and single call view

### ISSUE THREAD

**Issue by justinmihigo** [atlp-rwanda/commanders-rn-medica#71]
#### Description

As a developer my task is to create the screens for showing all the calls took place between a doctor and a patient, make the UI that can list those conversations, and also the one for viewing a single conversation. A user can also do certain operations like deleting the conversation, or download it.

#### Tasks

- [x] Create voice calls history screen
- [x] Create single call view
- [x] Create a menu for downloading and deleting the conversation

#### Definition of Done

- All screens looks and behaves as the designs
-  A user can listen to the audio
- Navigation between pages works correctly

#### Developer Notes

N/A

#### Related Issues

- N/A

#### Screens to be implemented
![image](https://github.com/atlp-rwanda/commanders-rn-medica/assets/118519513/d9bf8493-1798-4b23-8fee-bf663e32c167)
