### ISSUE TITLE
Feature: appointment voice call

### ISSUE THREAD

**Issue by fredshema** [atlp-rwanda/commanders-rn-medica#75]
#### Description

After making an appointment with a doctor and chose the voice call package, you can start a voice call with your doctor using these screens

#### Tasks

- [x] Design appointment summary page
- [x] Design call screen
- [x] Design call ended screen 

#### Developer Notes

N/A

#### Related Issues

- N/A

#### Screens to be implemented

<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/a3134f75-36f6-4bb4-82cc-9eacb0b79fc0" width="250"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/f020cf49-9293-4c03-a821-54585e68aba0" width="250"/>
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/4eb857c8-893c-489c-9a4c-56c176c8d947" width="250"/>

#### Definition of Done

- All screens looks and behaves as the designs
- Navigation between pages works correctly
