### ISSUE TITLE
Chore:Setup Github Badges

### ISSUE THREAD

**Issue by Emmyfrank** [atlp-rwanda/commanders-rn-medica#9]
## Badge

[![PROJECT STSTUS](https://img.shields.io/badge/Chole%20Status-In%20Progress-yellow)](https://your-project-url)

### Tasks

- [x] Create a badge indicating the status of the "Chole" project
- [x] Embed the badge in the GitHub issues, pull requests, or README file
- [x] Verify that the badge link directs to the correct URL

### Description

As a developer, I am tasked with creating a badge to indicate the status of our project "Chole".

### How to Use

1. Create the badge using the provided template.
2. Embed the badge in the appropriate location within the project.
3. Verify that clicking the badge redirects to the correct URL.

### Example

![Example Badge](https://img.shields.io/badge/Chole%20Status-In%20Progress-yellow)

Simply you will be copying the markdown code below and paste it wherever you want to display the badge:

```markdown
[![Chole Project Status](https://img.shields.io/badge/Chole%20Status-In%20Progress-yellow)](https://your-project-url)
