### ISSUE TITLE
Feature: Sign in with google OAuth

### ISSUE THREAD

**Issue by fredshema** [atlp-rwanda/commanders-rn-medica#95]
#### Description

This is an implementation of google OAuth where a user will log in the app using their google account.

#### Tasks

- [x] Create OAuth clients in google cloud platform
- [x] Configure and enable google OAuth on supabase or setup env
- [x] Implement the OAuth flow in the designs.

#### Developer Notes

N/A

#### Related Issues

N/A

#### Definition of Done

- Any user with a google account should be able to sign in
- After signing in a user should be redirected to the home page
